title = "Matías Schrauf"
baseURL = "https://schrauf.github.io"
theme = "bilberry-hugo-theme"

enableRobotsTXT = true

# Change to one of your content languages definded at the end.
DefaultContentLanguage = "en"

# Enable / Disable Google Analytics statistics for your site
googleAnalytics = ""

# Enable / Disable comments on the articles via Disqus.
# disqusShortname = "bilberry-hugo-theme"

[params]
  # Favicon for the browser's favorites and tabs
  favicon = "" # set a favicon icon

  # Custom CSS / JS modules that will be imported by the template.
  # Files are relative to the static/ directory or a URL.
  # Files are imported in the order they appear here, after
  # theme.css and theme.js, respectively.
  css_modules = []
  js_modules = []

  # Description and meta data for the search engines
  author = "Schrauf"
  description = ""
  keywords = ""

  # How many articles should be displayed at once?
  paginate = 7

  # Enable / Disable MathJax
  enable_mathjax    = true

  # Enable / Disable algolia search
  algolia_search    = false
  # algolia_appId     = "Y2C4RWMPXW"
  # algolia_apiKey    = "50ea7f8c41c0ad233926e0be2b769ed1"
  # algolia_indexName = "default-content"
    # Set this option to false if you want to search within all articles in all languages at once
  #  algolia_currentLanguageOnly = true

  # Header configuration
    # your subtitle if you want to use any
    subtitle = ""

    # if you want to use gravatar for the header image
    # gravatarEMail = "code@lednerb.de"

    # set an path to the image file you want to use | overwrites gravatar
    customImage = "bioluminiscent_fern_square.png"

    # always display the top navigation (with pages and search) on non-mobile screens
    permanentTopNav = true

    # show a language chooser in the header
    showHeaderLanguageChooser = true


  # Footer configuration
    showFooter = true

    # How many articles should be displayed at latest posts in the footer?
    # Set to -1 to hide the 'Latest Posts' column
    amountLatestPostsInFooter = 5

    # How many categories should be displayed in the footer section?
    # Set to -1 to hide the 'Categories' column
    amountCategoriesInFooter = 5

    # show a language chooser in the header
    showFooterLanguageChooser = true

    # social media profile urls for the footer links
    showSocialMedia = true

    facebook   = ""
    twitter    = ""
    googleplus = ""
    pinterest  = ""
    instagram  = ""
    tumblr     = ""
    youtube    = ""
    vimeo      = ""
    github     = "https://github.com/schrauf"
    xing       = ""
    linkedin   = ""

    # credits line configuration
    copyrightBy = "by M.F. Schrauf"
    copyrightUseCurrentYear = false  # set to true to always display the current year in the copyright
    copyrightYearOverride = "2018"
    copyrightUrl = "https://github.com/schrauf"
    creditsText = "Bilberry Hugo Theme"
    creditsUrl = "https://github.com/Lednerb/bilberry-hugo-theme"


# customize your available languages for your multi-langual site
# or delete the [Languages] blog to use the theme with only one supported language
[Languages]
  [Languages.en]
    weight = 1
  [Languages.es]
    weight = 2

# don't change anything below
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"

[outputs]
  home = [ "HTML", "JSON", "RSS" ]
  page = [ "HTML" ]

